refresh_rate: 30 seconds
appenders:
  stdout:
    kind: console
  orders:
    kind: file
    path: "log/orders.log"
    encoder:
      pattern: "{d} - {m}{n}"
root:
  level: info
  appenders:
    - orders
    - stdout
loggers:
  app::backend::db:
    level: info
  app::orders:
    level: info
    appenders:
      - orders
    additive: false
